"""references_4

Revision ID: 5319f55785fc
Revises: f4ff19a46fdf
Create Date: 2023-08-18 17:10:04.167040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5319f55785fc'
down_revision: Union[str, None] = 'f4ff19a46fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_department_presentation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_department_presentation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type_department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('address_index', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['ref_region.id'], name='ref_department_presentation_region_id_fkey'),
    sa.ForeignKeyConstraint(['type_department_id'], ['ref_type_department.id'], name='ref_department_presentation_type_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ref_department_presentation_pkey'),
    sa.UniqueConstraint('name', name='ref_department_presentation_name_key')
    )
    # ### end Alembic commands ###
