"""refactor_debtor

Revision ID: b1f91837c283
Revises: 5319f55785fc
Create Date: 2023-08-18 20:41:32.443027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f91837c283'
down_revision: Union[str, None] = '5319f55785fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'overdue_od')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('overdue_od', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
