"""refactor_debtor_2

Revision ID: 282501a41664
Revises: b1f91837c283
Create Date: 2023-08-18 20:43:13.758295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282501a41664'
down_revision: Union[str, None] = 'b1f91837c283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('overdue_od', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'overdue_od')
    # ### end Alembic commands ###
