"""tasks

Revision ID: 7e5bfb99995c
Revises: af476d8babbb
Create Date: 2023-08-21 19:14:31.067483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5bfb99995c'
down_revision: Union[str, None] = 'af476d8babbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('section_card_debtor_id', sa.Integer(), nullable=True),
    sa.Column('type_statement_id', sa.Integer(), nullable=True),
    sa.Column('date_task', sa.DATE(), nullable=True),
    sa.Column('timeframe', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_statement', sa.DATE(), nullable=True),
    sa.Column('track_num', sa.String(length=50), nullable=True),
    sa.Column('date_answer', sa.DATE(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ),
    sa.ForeignKeyConstraint(['name_id'], ['ref_task.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['ref_result_statement.id'], ),
    sa.ForeignKeyConstraint(['section_card_debtor_id'], ['ref_section_card_debtor.id'], ),
    sa.ForeignKeyConstraint(['type_statement_id'], ['ref_type_statement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
