"""ref_task_2

Revision ID: f3eb32e2ac9d
Revises: 7e5bfb99995c
Create Date: 2023-08-21 21:00:15.497734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eb32e2ac9d'
down_revision: Union[str, None] = '7e5bfb99995c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_task', sa.Column('type_statement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ref_task', 'ref_type_statement', ['type_statement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_task', type_='foreignkey')
    op.drop_column('ref_task', 'type_statement_id')
    # ### end Alembic commands ###
