"""registries

Revision ID: 264d01eaa8b3
Revises: f3eb32e2ac9d
Create Date: 2023-08-24 16:16:57.934892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264d01eaa8b3'
down_revision: Union[str, None] = 'f3eb32e2ac9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('name_field', sa.String(length=50), nullable=False),
    sa.Column('headers', sa.String(length=100), nullable=False),
    sa.Column('headers_key', sa.String(length=50), nullable=False),
    sa.Column('width_field', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headers')
    )
    op.create_table('registry_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registry_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=50), nullable=True),
    sa.Column('registry_structure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registry_structure'], ['registry_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_filters')
    op.drop_table('registry_structures')
    op.drop_table('registry_headers')
    # ### end Alembic commands ###
