"""rename dir_folder

Revision ID: ee2e2757c2d0
Revises: 9ec6aebe60bb
Create Date: 2023-08-29 20:39:23.540343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2e2757c2d0'
down_revision: Union[str, None] = '9ec6aebe60bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('dir_folder',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=150), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('docs_folder',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=150), nullable=False),
    # sa.Column('folder_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['folder_id'], ['dir_folder.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('dir_form',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('credit_dir_id', sa.Integer(), nullable=True),
    # sa.Column('docs_folder_id', sa.Integer(), nullable=True),
    # sa.Column('path', sa.String(length=200), nullable=True),
    # sa.ForeignKeyConstraint(['credit_dir_id'], ['dir_credit.id'], ),
    # sa.ForeignKeyConstraint(['docs_folder_id'], ['docs_folder.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('dir_form')
#     op.drop_table('docs_folder')
#     op.drop_table('dir_folder')
    # ### end Alembic commands ###
