"""Refactoring debtor

Revision ID: 3472231e3ef1
Revises: d4756b728e5f
Create Date: 2023-09-16 10:21:04.911803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3472231e3ef1'
down_revision: Union[str, None] = 'd4756b728e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor', sa.Column('tribunal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debtor', 'ref_tribunal', ['tribunal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debtor', type_='foreignkey')
    op.drop_column('debtor', 'tribunal_id')
    # ### end Alembic commands ###
