"""Refactoring tribunal name

Revision ID: c47919f9ea7f
Revises: 357f1d7b1ea1
Create Date: 2023-09-16 19:15:30.841126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47919f9ea7f'
down_revision: Union[str, None] = '357f1d7b1ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ref_tribunal_name_key', 'ref_tribunal', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ref_tribunal_name_key', 'ref_tribunal', ['name'])
    # ### end Alembic commands ###
