"""Refactoring docs_folder

Revision ID: b9348b47eac8
Revises: 007f432f8aeb
Create Date: 2023-09-23 19:43:24.333402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9348b47eac8'
down_revision: Union[str, None] = '007f432f8aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defolt_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['dir_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dir_form')
    op.add_column('docs_folder', sa.Column('credit_dir_id', sa.Integer(), nullable=True))
    op.add_column('docs_folder', sa.Column('path', sa.String(length=200), nullable=True))
    op.drop_constraint('docs_folder_folder_id_fkey', 'docs_folder', type_='foreignkey')
    op.create_foreign_key(None, 'docs_folder', 'dir_credit', ['credit_dir_id'], ['id'])
    op.drop_column('docs_folder', 'folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs_folder', sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'docs_folder', type_='foreignkey')
    op.create_foreign_key('docs_folder_folder_id_fkey', 'docs_folder', 'dir_folder', ['folder_id'], ['id'])
    op.drop_column('docs_folder', 'path')
    op.drop_column('docs_folder', 'credit_dir_id')
    op.create_table('dir_form',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credit_dir_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('docs_folder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credit_dir_id'], ['dir_credit.id'], name='dir_form_credit_dir_id_fkey'),
    sa.ForeignKeyConstraint(['docs_folder_id'], ['docs_folder.id'], name='dir_form_docs_folder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dir_form_pkey')
    )
    op.drop_table('defolt_docs')
    # ### end Alembic commands ###
