"""Refactoring docs_folder_2

Revision ID: d14bcf6b0527
Revises: b9348b47eac8
Create Date: 2023-09-24 12:04:37.213552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14bcf6b0527'
down_revision: Union[str, None] = 'b9348b47eac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dir_folder', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('docs_folder', sa.Column('name_folder', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs_folder', 'name_folder')
    op.alter_column('dir_folder', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
