"""Create finance

Revision ID: 2940874fbff7
Revises: 7ca69f6c4853
Create Date: 2023-09-28 15:56:16.805527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2940874fbff7'
down_revision: Union[str, None] = '7ca69f6c4853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creditor', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('summa', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('date_end', sa.DATE(), nullable=False),
    sa.Column('loan_repayment_procedure', sa.String(length=200), nullable=True),
    sa.Column('dividends_payment_procedure', sa.String(length=200), nullable=True),
    sa.Column('balance_debt', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_expenses_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('summa', sa.Integer(), nullable=True),
    sa.Column('expenses_category_id', sa.Integer(), nullable=True),
    sa.Column('payment_purpose', sa.String(length=150), nullable=True),
    sa.Column('cession_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cession_id'], ['cession.id'], ),
    sa.ForeignKeyConstraint(['expenses_category_id'], ['ref_expenses_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('ref_expenses_category')
    op.drop_table('lending')
    # ### end Alembic commands ###
