"""Refactot cession add lending_id

Revision ID: 44e3384bf47f
Revises: 2940874fbff7
Create Date: 2023-09-28 20:05:07.996951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e3384bf47f'
down_revision: Union[str, None] = '2940874fbff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cession', sa.Column('lending_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cession', 'lending', ['lending_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cession', type_='foreignkey')
    op.drop_column('cession', 'lending_id')
    # ### end Alembic commands ###
