"""Добавил parent_id в credit

Revision ID: ac4a232a6214
Revises: 44e3384bf47f
Create Date: 2023-11-01 19:22:26.876022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4a232a6214'
down_revision: Union[str, None] = '44e3384bf47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('docs_folder', 'path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docs_folder', 'path',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('credit', 'parent_id')
    # ### end Alembic commands ###
