"""Debtor

Revision ID: cfcf8ba6d3ca
Revises: c18aabe4b3e1
Create Date: 2023-08-10 19:23:01.312489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcf8ba6d3ca'
down_revision: Union[str, None] = 'c18aabe4b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('summa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cedent', sa.String(length=100), nullable=True),
    sa.Column('cessionari', sa.String(length=100), nullable=True),
    sa.Column('date_old_cession', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('debtor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name_1', sa.String(length=80), nullable=False),
    sa.Column('first_name_1', sa.String(length=20), nullable=False),
    sa.Column('second_name_1', sa.String(length=20), nullable=True),
    sa.Column('last_name_2', sa.String(length=80), nullable=True),
    sa.Column('first_name_2', sa.String(length=20), nullable=True),
    sa.Column('second_name_2', sa.String(length=20), nullable=True),
    sa.Column('pol', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('pensioner', sa.Boolean(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=200), nullable=True),
    sa.Column('passport_series', sa.String(length=5), nullable=True),
    sa.Column('passport_num', sa.String(length=6), nullable=True),
    sa.Column('passport_date', sa.DATE(), nullable=True),
    sa.Column('passport_department', sa.String(length=200), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('snils', sa.String(length=14), nullable=True),
    sa.Column('address_1', sa.String(length=200), nullable=True),
    sa.Column('address_2', sa.String(length=200), nullable=True),
    sa.Column('index_add_1', sa.String(length=6), nullable=True),
    sa.Column('index_add_2', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creditor', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=True),
    sa.Column('date_end', sa.String(length=100), nullable=True),
    sa.Column('summa_by_cession', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('summa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_od', sa.Boolean(), nullable=True),
    sa.Column('overdue_percent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percent_of_od', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gov_toll', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.Column('cession_id', sa.Integer(), nullable=True),
    sa.Column('status_cd_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('credits_old', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cession_id'], ['cession.id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creditor'),
    sa.UniqueConstraint('number')
    )
    op.create_table('ref_status_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_status_credit')
    op.drop_table('credit')
    op.drop_table('debtor')
    op.drop_table('cession')
    # ### end Alembic commands ###
