"""create date_start_functions

Revision ID: 4119eb506137
Revises: 5cf0285fed84
Create Date: 2023-12-21 21:31:48.711981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4119eb506137'
down_revision: Union[str, None] = '5cf0285fed84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_start_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('number_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agreement', sa.Column('control', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreement', 'control')
    op.drop_table('date_start_functions')
    # ### end Alembic commands ###
