"""refactor_expenses

Revision ID: 8a28077011b2
Revises: 4119eb506137
Create Date: 2023-12-29 16:09:54.408148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a28077011b2'
down_revision: Union[str, None] = '4119eb506137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date_accrual', sa.DATE(), nullable=True))
    op.add_column('expenses', sa.Column('status_pay', sa.Boolean(), nullable=True))
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('expenses', 'status_pay')
    op.drop_column('expenses', 'date_accrual')
    # ### end Alembic commands ###
