"""legal_work-add_date_legal

Revision ID: 0f9f0b937afc
Revises: 8a28077011b2
Create Date: 2024-01-06 16:28:36.675971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9f0b937afc'
down_revision: Union[str, None] = '8a28077011b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_work', sa.Column('legal_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_work', 'legal_date')
    # ### end Alembic commands ###
