"""References_V1

Revision ID: 7f1d03d69ca1
Revises: cfcf8ba6d3ca
Create Date: 2023-08-10 20:51:31.806670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1d03d69ca1'
down_revision: Union[str, None] = 'cfcf8ba6d3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_claimer_ed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_financial_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organisation_fm', sa.String(length=200), nullable=True),
    sa.Column('address_1', sa.String(length=200), nullable=True),
    sa.Column('address_2', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_reason_cansel_ed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_reason_end_ep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_status_ed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_tribunal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class_code', sa.String(length=9), nullable=False),
    sa.Column('oktmo', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_type_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_type_ed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_type_state_duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_type_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ref_department_presentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type_department_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('address_index', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['ref_region.id'], ),
    sa.ForeignKeyConstraint(['type_department_id'], ['ref_type_department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('cession_name_key', 'cession', type_='unique')
    op.drop_constraint('cession_number_key', 'cession', type_='unique')
    op.drop_constraint('credit_creditor_key', 'credit', type_='unique')
    op.drop_constraint('credit_number_key', 'credit', type_='unique')
    op.create_foreign_key(None, 'credit', 'ref_status_credit', ['status_cd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit', type_='foreignkey')
    op.create_unique_constraint('credit_number_key', 'credit', ['number'])
    op.create_unique_constraint('credit_creditor_key', 'credit', ['creditor'])
    op.create_unique_constraint('cession_number_key', 'cession', ['number'])
    op.create_unique_constraint('cession_name_key', 'cession', ['name'])
    op.drop_table('ref_department_presentation')
    op.drop_table('ref_type_statement')
    op.drop_table('ref_type_state_duty')
    op.drop_table('ref_type_ed')
    op.drop_table('ref_type_department')
    op.drop_table('ref_tribunal')
    op.drop_table('ref_status_ed')
    op.drop_table('ref_region')
    op.drop_table('ref_reason_end_ep')
    op.drop_table('ref_reason_cansel_ed')
    op.drop_table('ref_financial_manager')
    op.drop_table('ref_claimer_ed')
    # ### end Alembic commands ###
