"""Directory_docs

Revision ID: af46445c6a57
Revises: 7f1d03d69ca1
Create Date: 2023-08-15 18:09:43.689919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af46445c6a57'
down_revision: Union[str, None] = '7f1d03d69ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cession', 'path')
    op.add_column('ref_tribunal', sa.Column('gaspravosudie', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_tribunal', 'gaspravosudie')
    op.add_column('cession', sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
