"""collection_debts

Revision ID: 7630e248fa37
Revises: 13a8546341e2
Create Date: 2023-08-16 20:41:13.173053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7630e248fa37'
down_revision: Union[str, None] = '13a8546341e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('date_of_receipt_ed', sa.DATE(), nullable=True),
    sa.Column('date_decision', sa.DATE(), nullable=True),
    sa.Column('type_ed_id', sa.Integer(), nullable=True),
    sa.Column('status_ed_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('summa_debt_decision', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state_duty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('succession', sa.DATE(), nullable=True),
    sa.Column('date_entry_force', sa.DATE(), nullable=True),
    sa.Column('claimer_ed_id', sa.Integer(), nullable=True),
    sa.Column('tribunal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['claimer_ed_id'], ['ref_claimer_ed.id'], ),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ),
    sa.ForeignKeyConstraint(['status_ed_id'], ['ref_status_ed.id'], ),
    sa.ForeignKeyConstraint(['tribunal_id'], ['ref_tribunal.id'], ),
    sa.ForeignKeyConstraint(['type_ed_id'], ['ref_type_ed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ifns_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_inform', sa.DATE(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('inn', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_department_id', sa.Integer(), nullable=True),
    sa.Column('department_presentation_id', sa.Integer(), nullable=True),
    sa.Column('executive_document_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DATE(), nullable=True),
    sa.Column('date_return', sa.DATE(), nullable=True),
    sa.Column('date_end', sa.DATE(), nullable=True),
    sa.Column('reason_cansel_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ),
    sa.ForeignKeyConstraint(['department_presentation_id'], ['ref_department_presentation.id'], ),
    sa.ForeignKeyConstraint(['executive_document_id'], ['executive_document.id'], ),
    sa.ForeignKeyConstraint(['reason_cansel_id'], ['ref_reason_cansel_ed.id'], ),
    sa.ForeignKeyConstraint(['type_department_id'], ['ref_type_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executive_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('summary_case', sa.String(length=50), nullable=True),
    sa.Column('date_on', sa.DATE(), nullable=True),
    sa.Column('date_end', sa.DATE(), nullable=True),
    sa.Column('reason_end_id', sa.Integer(), nullable=True),
    sa.Column('curent_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('summa_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gov_toll', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rosp_id', sa.Integer(), nullable=True),
    sa.Column('pristav', sa.String(length=50), nullable=True),
    sa.Column('pristav_phone', sa.String(length=50), nullable=True),
    sa.Column('date_request', sa.DATE(), nullable=True),
    sa.Column('object_ep', sa.String(length=100), nullable=True),
    sa.Column('executive_document_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('claimer', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.id'], ),
    sa.ForeignKeyConstraint(['executive_document_id'], ['executive_document.id'], ),
    sa.ForeignKeyConstraint(['reason_end_id'], ['ref_reason_end_ep.id'], ),
    sa.ForeignKeyConstraint(['rosp_id'], ['ref_department_presentation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ifns_bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ifns_inform', sa.Integer(), nullable=True),
    sa.Column('debtor', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=150), nullable=True),
    sa.Column('bik', sa.String(length=9), nullable=True),
    sa.Column('inn', sa.String(length=10), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('date_account', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['debtor'], ['debtor.id'], ),
    sa.ForeignKeyConstraint(['ifns_inform'], ['ifns_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ifns_bank_account')
    op.drop_table('executive_productions')
    op.drop_table('collection_debt')
    op.drop_table('ifns_information')
    op.drop_table('executive_document')
    # ### end Alembic commands ###
