"""Cession_refactor

Revision ID: c48f7970f292
Revises: 7630e248fa37
Create Date: 2023-08-17 21:28:47.579417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48f7970f292'
down_revision: Union[str, None] = '7630e248fa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cession', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cession', type_='unique')
    # ### end Alembic commands ###
